import pandas as pd
df=pd.read_csv("employee.csv")
print(df.head())
print(df.info())
print(df.shape)
print(df.isnull().sum())
df["city"]=df["city"].str.lower().str.strip()
df["department"]=df["department"].str.lower().str.strip()
print(df["city"].unique())
print(df["department"].unique())
print(df["city"].value_counts())
print(df["department"].value_counts())
df["join_date"]=pd.to_datetime(df["join_date"])
df["review_date"]=pd.to_datetime(df["review_date"])
print(df.info())
df["tenure_years"]=(df["review_date"]-df["join_date"]).dt.days/365
df["tenure_years"]=df["tenure_years"].round(1)
df["join_year"]=df["join_date"].dt.year
df["quarter"]=df["join_date"].dt.to_period("Q")
print(df)
df["exp_bands"]=df["tenure_years"].apply(lambda x: "fresher" if x<3 else "medium" if x<7 else "expert")
print(df)
print(df[["tenure_years","exp_bands"]].head())
print(df["exp_bands"].value_counts())
df.info()
print(df.groupby("department")["performance_score"].mean().sort_values(ascending=False).round(1))
print(df.groupby(pd.cut(df["attendance_pct"],bins=[0,75,85,90]))["performance_score"].mean().round(1))
print(df.groupby(pd.cut(df["attendance_pct"], bins=[0,75,85,90]), observed=False)["performance_score"].mean().round(1))
print(df.groupby("exp_bands")["performance_score"].mean().sort_values(ascending=False).round(1))
print(df.groupby(pd.cut(df["tenure_years"], bins=[0,3,7,10]), observed=False)["performance_score"].mean().sort_values(ascending=False).round(1))
